### ISSUE TITLE
Symbol’s function definition is void: bibtex-completion-get-value-by-key

### ISSUE THREAD

**Issue by emacsbliss** [yuchen-lea/org-media-note#14]
seems couldn't find this function in helm-bibtex.

I think this works for me:
```
         (entry (bibtex-completion-get-entry key))
         (formats (bibtex-completion-get-value "formats" entry))
```

**Comment by emacsbliss** [comment]
thanks for prompt fixing!

**Comment by yuchen-lea** [comment]
Oh no...I didn't notice that it use my own customized functions when I make this a seperate package.  org-ref integration is just for my personal use at first. Thanks for pointing this out! Now that there're other people using org-ref integration, I will improve the doc about this 😂
