### ISSUE TITLE
Error: "failed to provide feature ‘org-media-note.el’""

### ISSUE THREAD

**Issue by AtomicNess123** [yuchen-lea/org-media-note#17]
Great package. Looking forward to being able to use it :)
For the time being I am getting this error when starting my Emacs:

`Debugger entered--Lisp error: (error "Loading file /path.to/org-media-note-master/org-media-note.el failed to provide feature ‘org-media-note.el’")`

My init config:

```emacs-lisp
(add-to-list 'load-path "path.to/org-media-note-master")
(require 'org-media-note.el)
(setq org-media-note-screenshot-image-dir "path.to/imgs/")  ;; Folder to save screenshot
(setq org-media-note-use-refcite-first t)  ;; use videocite link instead of video link if possible
```

Thanks for the help!

**Comment by yuchen-lea** [comment]
I think it should be `(require 'org-media-note)`

**Comment by AtomicNess123** [comment]
Damn... silly me! Thanks!
