### ISSUE TITLE
Adding videos to bib file

### ISSUE THREAD

**Issue by promisedlandt** [yuchen-lea/org-media-note#18]
Hello Yuchen,

in the readme you mention "quick open related media file in org-ref note (file path is got from bib file)".

I can not figure out how to add a local video file to the bib file. Could you give me a quick description of how you do it, please?
I understand it's not a problem with org-media-note, but I did not know how I can contact you otherwise.

**Comment by yuchen-lea** [comment]
I recommend to use some apps which support bib export to manage videos, like calibre or zotero. 

The workflow is like:
- calibre or zotero: grab or edit the metadata of media file, export bib file
- org-ref: build the connection between bib file and org-mode
- org-media-note: play the corresponding media file

**Comment by promisedlandt** [comment]
Thank you, that works well!
