### ISSUE TITLE
Does not play well with WM

### ISSUE THREAD

**Issue by OrionRandD** [yuchen-lea/org-media-note#2]
It is ok.
But seems not to play well with WM.
e.g. I use Stumpwm and it does not T toggle on top and other keys do not work as well  :(
Probably will not play well with Xmonad and I3WM.
Perhaps you should add a note about not functioning well with WM/TW...

**Comment by yuchen-lea** [comment]
Sorry, I can't reproduce the issue since I don't use WM. In fact, it's only a wrapper of mpv. Maybe you can test whether it works well in pure mpv player.

**Comment by joshcho** [comment]
This package is very cool and would be even cooler if it worked with WM (using Xmonad). I will take a look at this and submit a pull request.

**Comment by yuchen-lea** [comment]
@joshcho 
Glad to here this! I'm not familiar with WM, your contributions are welcome!
