### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by progfolio** [yuchen-lea/org-media-note#23]
Running flymake or flycheck mode (in combination with checkdoc) will prevent errors and keep code consistent with the elisp style guide.

See: #21

**Comment by yuchen-lea** [comment]
Words are powerless to express my gratitude! 

Where can I study the elisp code style?

**Comment by progfolio** [comment]
Running `M-x checkdoc` in an elisp project is one way.
There are also these resources:

https://www.emacswiki.org/emacs/CodingStyle
https://github.com/bbatsov/emacs-lisp-style-guide
https://github.com/riscy/melpazoid

**Comment by yuchen-lea** [comment]
Useful info! Thank you so much!
