### ISSUE TITLE
"o: Open file": Symbol’s function definition is void: org-media-note-get-media-file-by-key

### ISSUE THREAD

**Issue by SpiritInAShell** [yuchen-lea/org-media-note#24]
When calling with M+x `org-media-note-hydra/body` I get the message:
`Symbol’s function definition is void: org-media-note-get-media-file-by-key`

**Comment by SpiritInAShell** [comment]
It seems, that if I use `M+x mpv-play` to open a file, and then call `org-media-note-hydra/body`, I can control the playback and use the functions like timestamp insertion.

**Comment by yuchen-lea** [comment]
Sorry for the late reply. I can't reproduce your issue. 

Have you solved this? If not, can you show me your config?

**Comment by yuchen-lea** [comment]
Duplicate of #25
