### ISSUE TITLE
t m   keys

### ISSUE THREAD

**Issue by OrionRandD** [yuchen-lea/org-media-note#3]
t m - in doom - is doing this
Org-Media-Note mode enabled
Org-Media-Note mode disabled
H-v  activates Visual mode
s  gives me  ‘get_property’ failed: property unavailable
:(

**Comment by yuchen-lea** [comment]
`
s gives me ‘get_property’ failed: property unavailable 
`
This happens when mpv cannot find subtitle for current playing file. e35762e provides a more understandable message.

The other part confused me... it seems you haven't bind H-v to org-media-note-hydra/body? You can bind org-media-note-hydra/body to any key you like, then follow the hydra hint.

**Comment by OrionRandD** [comment]
Oh. Thx for replying. I have changed to another package to make notes in Emacs.
You can close this issue,
if you want.

**Comment by hummuscience** [comment]
@yuchen-lea I got the same error when trying to play an online video (https://www.youtube.com/watch?v=Nk0H3o-hRMA&list=PLUl4u3cNGP60IKRN_pFptIBxeiMc0MCJP&index=5)

it has closed caption subtitles but no subtitles otherwise. Any idea what is causing this?

**Comment by yuchen-lea** [comment]
The ability to play online videos, acquisition of subtitles, and other functionalities regarding playing media files are all implemented by mpv.
You can try running

`(mpv-start 'https://www.youtube.com/watch?v=Nk0H3o-hRMA&list=PLUl4u3cNGP60IKRN_pFptIBxeiMc0MCJP&index=5')`

I can play videos and take notes normally, but there are no subtitles. 

It seems that acquiring subtitles for online videos requires:

1. subtitle can be extracted by 'youtube-dl' or 'yt-dlp'
2. editing the configuration of mpv

I only use it for playing local videos and youtube streaming is unbearable slow.  If you have any progress, contributions are greatly welcome. if there's anything I can do to help you out let me know

[How to play YouTube videos with MPV subtitles\? \- Super User](https://superuser.com/questions/1405266/how-to-play-youtube-videos-with-mpv-subtitles "How to play YouTube videos with MPV subtitles? - Super User")
[mpv play youtube auto generated subtitles \- YouTube](https://www.youtube.com/watch?v=QDY7T5foS3I "mpv play youtube auto generated subtitles - YouTube")
[How to select english subtitles on YouTube with \"\-\-slang\" · Issue \#10245 · mpv\-player\/mpv](https://github.com/mpv-player/mpv/issues/10245 "How to select english subtitles on YouTube with \"--slang\" · Issue #10245 · mpv-player/mpv")
[Captions when playing YouTube videos with MPV\? \: linuxquestions](https://www.reddit.com/r/linuxquestions/comments/nyqxf7/captions_when_playing_youtube_videos_with_mpv/ "\(2\) Captions when playing YouTube videos with MPV? : linuxquestions")
