### ISSUE TITLE
b 站 多p视频能支持嘛？

### ISSUE THREAD

**Issue by bommbo** [yuchen-lea/org-media-note#32]
你好，非常感谢这么好的包。我想请教下，这个能支持b站多p的视频嘛？

**Comment by yuchen-lea** [comment]
我自己不太直接用在线视频，都是下载到NAS然后做笔记。

简单试了一下，不太清楚这样是否满足你的需求：

1. 可以打开诸如 https://www.bilibili.com/video/BV1EW411u7th?p=1 的在线视频，进行笔记
2. 点击插入的时间戳链接，可以跳转到在线视频的对应位置 （速度取决于网速）

> - [[video:https://www.bilibili.com/video/BV1EW411u7th?p=1#0:00:10][0:00:10]]
> - [[video:https://www.bilibili.com/video/BV1EW411u7th?p=1#0:00:13][0:00:13]]
> 
> - [[video:https://www.bilibili.com/video/BV1EW411u7th?p=2#0:00:07][0:00:07]]
> - [[video:https://www.bilibili.com/video/BV1EW411u7th?p=2#0:00:21][0:00:21]]

**Comment by bommbo** [comment]
貌似有些问题，可能是因为mpv用的youtube-dl不支持多p

**Comment by yuchen-lea** [comment]
我不太清楚你说的问题具体是指什么。最好可以详细描述下：

- 实际操作步骤
- 期待的行为
- 实际的行为

如果能有具体的url实例就更好了。

**Comment by bommbo** [comment]
比如说：
[[video:https://www.bilibili.com/video/BV1EW411u7th?p=1#0:00:01][0:00:01]]
[[video:https://www.bilibili.com/video/BV1EW411u7th?p=2#0:00:01][0:00:01]]
[[video:https://www.bilibili.com/video/BV1EW411u7th?p=3#0:00:01][0:00:01]
其实这几个时间戳，点开都是同一个视频。

**Comment by bommbo** [comment]
抱歉啊，我找到解决办法了，yt-dlp https://github.com/yt-dlp/yt-dlp 是支持多p视频的，但是 youtube-dl 不支持，我改了依赖就好了，在mpv.conf下添加script-opts=ytdl_hook-ytdl_path=yt-dlp就可以了， https://www.reddit.com/r/mpv/comments/opoorx/mpv_with_ytdlp/。谢谢关注这个问题，我关闭这个问题了。

**Comment by yuchen-lea** [comment]
赞！恭喜找到解决方案，我对线上视频这部分用得不太多。你有时间把你的解决方案补充到中文帮助中么？相信能帮到不少有类似需求的人。
