### ISSUE TITLE
Noting need to download youtube-dl

### ISSUE THREAD

**Issue by joshcho** [yuchen-lea/org-media-note#34]
I was struggling to view online links for mpv, and discovered you actually need youtube-dl to view online links in mpv. I think this may be worth noting for people who are not familiar with mpv.

**Comment by hwiorn** [comment]
youtube-dl is a python library and tool and it can be installed by OS package manager such as apt, yum(dnf), homebrew and pip. Or you can install it to your own OS manually.

For now, I think the best is checking the `youtube-dl` and showing the message for user to install `youtube-dl` themselves.

https://github.com/kljohann/mpv.el/issues/11#issuecomment-1005980159

**Comment by yuchen-lea** [comment]
Already added to warning, Thanks!
