### ISSUE TITLE
error when taking a screenshot

### ISSUE THREAD

**Issue by DarkBuffalo** [yuchen-lea/org-media-note#38]
hi @yuchen-lea 
First of all it must be said that this package is an excellent job !

Configuration
- GNU Emacs 28.1.50
- Org mode version 9.5.3
- Linux (Arch)
- mpv 0.34.1

Error when taking a screenshot:
‘screenshot-to-file’ failed: error running command

**Comment by yuchen-lea** [comment]
Sorry for the late reply, I was busy working recently.

I just call [mpv.io](https://mpv.io/manual/master/#command-interface-screenshot-to-file "mpv.io") native command to take screenshot, so you can check:

1. Does screenshot work in mpv: by default, take a screenshot with the s key 
2. Does `mpv-run-command` work in emacs

**Comment by impress-lt** [comment]
I had same issue -  `‘screenshot-to-file’ failed: error running command` until i created screenshot directory myself. If directory does not exist it cannot take screenshot.

**Comment by yuchen-lea** [comment]
@impress-lt Thanks for pointing it out! Now, it will create the dir if `org-media-note-screenshot-image-dir` doesn't exsists, when set `org-media-note-screenshot-save-method` to `directory`.

Let me know if you still have problems with it.

**Comment by DarkBuffalo** [comment]
thanks, it works. good work
