### ISSUE TITLE
What about add a new functionality to support cut video clip?

### ISSUE THREAD

**Issue by stardiviner** [yuchen-lea/org-media-note#40]
I think cut video clip functionality is a common scene for many users.
Would this extension be able to implement this feature?

Thanks for checking out.

**Comment by minwookhan** [comment]
thanks for your wonderful works.
it'd be good if i can resize the clipped image. :)

**Comment by yuchen-lea** [comment]
I feel that screenshots are more universal. I'm not so sure about video clips. 

There are many possibilities here, such as whether to save as a video or a GIF, the image quality, whether to save to a folder or insert directly into org-mode. If inserting into org-mode, should it be saved to attach or a specified folder? 

This seems to be very personalized, with many possible command-line implementations. Currently, not many users have requested this, and I don't use it myself, so I'm unsure whether to add it as a general feature. 

Nonetheless, utilizing org-mode to parse links, combined with the command line, should make implementation quite straightforward.

I'll reopen this if proved necessary.
