### ISSUE TITLE
org-media-note does not support mpv's resume playback

### ISSUE THREAD

**Issue by stardiviner** [yuchen-lea/org-media-note#58]
I hope org-media-note can support mpv resume playback by default.

**Comment by stardiviner** [comment]
I tried to config options:
```elisp
  (add-to-list 'org-media-note-mpv-general-options "--save-position-on-quit" 'append)
  (add-to-list 'org-media-note-mpv-general-options "--resume-playback=yes" 'append)
```
But it does not work. don't know why.

**Comment by yuchen-lea** [comment]
Clicking on the timestamp link will definitely jump to the corresponding time. 

So you mean you want to resume playback when calling `org-media-note-play-smart` when `org-media-note-mpv-general-options` is set?

Currently, start playing from the beginning is written within the code. I think this is why the settings of `org-media-note-mpv-general-options` are not taking effect

**Comment by stardiviner** [comment]
> So you mean you want to resume playback when calling `org-media-note-play-smart` when `org-media-note-mpv-general-options` is set?
> 
> Currently, start playing from the beginning is written within the code. I think this is why the settings of `org-media-note-mpv-general-options` are not taking effect

Yes, that's what I want. Usually I don't have time to finished watch full time of video, then I have to close it at first, then re-open it later. I think most people assume this behavior. I hope org-media-note can change this. WDYT?

**Comment by yuchen-lea** [comment]
I usually insert a timestamp link and then start playing from the timestamp next time.

But what you said makes sense. At least the current `org-media-note-play-smart` will make the settings of `org-media-note-mpv-general-options` not take effect. I will fix this as soon as possible.

But I haven't decided yet whether to use resume playback as the default setting, or just configure `org-media-note-mpv-general-options` like you do.

**Comment by stardiviner** [comment]
Or maybe consider add a new defcustom option if you like.

**Comment by yuchen-lea** [comment]
I didn't set resume playback as a defcustom option. This seems to be invalid for online videos. I haven't figured out its scope yet.
But now `org-media-note-mpv-general-options` should take effect

**Comment by stardiviner** [comment]
Thanks for quick patch!

I prefer the new transient interface, because it's compact, the pretty-hydra can't display all long UI in my vertical screen displayer.
