### ISSUE TITLE
Integration with org-attach

### ISSUE THREAD

**Issue by nanjigen** [yuchen-lea/org-media-note#6]
Another small convenience feature idea: When bringing up `org-media-note-hydra/body`, and pressing `o` for opening file brings up a lovely fuzzy search buffer, which defaults to looking inside the same folder of the file being visited. 

For those of us who use `org-attach` and its attach directory, accessing `org-attach-dir` while viewing a header in an org buffer would be very useful as a first place to search for a media file. Perhaps if `org-attach-dir` returns nil then the search could fallback to the root of the folder as it does now (this may be tricky as in some circumstances and configs, `org-attach-dir` may attempt to create the DIR, so getting the function to wait for a `nil` might fail and empty DIR's would get created in its wake).

This might also allow for screenshots to be saved in the location the media was sourced (i.e., the same `org-attach` DIR)

Thanks for you time and effort on this, its a great project

**Comment by yuchen-lea** [comment]
I don't use org-attach but this sounds reasonable. 

I need your help to clarify the user story: 

Let's suppose the attach-dir of heading `H` is `A`

1. if there is only one media file `M` in `A`, open `M` directly
2. if there are several media files in `A`, let user chose file from directory `A`
3. if there are no media files in `A`, fall back to original way.
4. In situation 1, when saving screenshot `P` of `M` to `A`:
  - under heading `H`, how do I insert the screenshot `P`?
  - Can I insert the screenshot `P` to other heading? 

I want to know your opinions on the above situations. Also, can you tell me what are variables which affect the behavior of `org-attach-dir`?

**Comment by nanjigen** [comment]
1 through 3 seem perfectly acceptable to me as a user.

I had not considered deeply enough the scenario in 4, sorry about that:

There is [org-attach-screenshot](https://github.com/dfeich/org-screenshot), which has various ways of dealing with the above, though I completely understand resistance to more external package requirements, but at the very least it is a working example. 

By default, after asking for a filename, the package will take a screenshot of the desktop (not needed for us as `mpv` is already doing that) and inserts a link into the buffer:
`[[file:../../.attach/51/e12241-991a-4bb1-9adb-1573add22d2b/screenshot-20210218-142543.png]]`

However, if we set the var `org-attach-screenshot-relative-links` to `nil`, we get the following link:
`[[file:/home/nanjigen/org/.attach/51/e12241-991a-4bb1-9adb-1573add22d2b/screenshot-20210218-143045.png]]`

The key point here is that the whole process uses an UUID (my preference), or a DIR specified by the `:ATTACH-DIR:` [property](https://orgmode.org/manual/Attachment-options.html) in the headers property-drawer. Either of the above style links can be moved to different headers, though I personally much prefer `org-attach-screenshot-relative-links` to be set to `t` so org files are usable across machines with different user names.

For me, the power of `org-attach` comes with its use of UUID's, as this allows for essentially a kind of flat directory structure - things are located by their org-header/UUID, not by their position in a FS hierarchy.

Does this help?

**Comment by yuchen-lea** [comment]
Thanks for the detailed explain! Update to the latest version and have a try ;D

Currently Supported:

1. when pressing `o` for opening file. behaves like 1 through 3 as we discussed above
2. when save screenshot, there are three new variables for customization:
   1. `org-media-note-screenshot-save-method` save to `org-media-note-screenshot-image-dir` or org-attach-dir
   2. `org-media-note-screenshot-link-type-when-save-in-attach-dir` when `org-media-note-screenshot-save-method` sets to attach, use file link or attachment link 
   3. `org-media-note-abbreviate-filename-function` use absolute or relative file path for file link
   
I keep the default value as previous, you have to customize these variables according to your need.

**Comment by nanjigen** [comment]
Thanks yuchen! 

2. and its configurations works well but I'm having trouble getting `o` to search inside the `attach-directory` for multiple files or open the only file - it simply runs the default behavior

**Comment by yuchen-lea** [comment]
Strange... It works on my computer. Please check:

1. already updated to the newest version
2. press `o` under the heading which has attach dir
3. open the org-media-note, and call `eval-buffer`. Or find function `org-media-note-mpv-smart-play`, run `eval-last-sexp` at the ending bracket. Then press `o` to see what happens.

If it still runs the default behavior, run `edebug-defun` on `org-media-note-mpv-smart-play`, then press `o` or directly call `org-media-note-mpv-smart-play`, then you will run into the edebug. Follow the step, check the value of media-files-in-attach-dir, this should be a list of media files in your attach-dir.

**Comment by nanjigen** [comment]
Thanks for the speedy response yuchen. After some testing, I've found that I can get the desired functionality when there are no other media files in the root of the folder the `.org` with the headline is. 

When there is just one file in the `attach-dir`, it will automatically open it. If there is more than one, it will offer a fuzzy search of the attachment folder.

However, when there are media files in that root folder, the search defaults back to search in that folder, instead of first checking whether there are files in the attachment directory of the headline at point.

**Comment by yuchen-lea** [comment]
Let's verify whether my understanding is correct: 

1. org file `F` is in dir `root`
2. the heading `H` in org file `F` has an attach dir `attach-dir`

Then:
1. when there are no media files in `root`, everything works as expected.
2. when there are media files in `root`, it will open the `root` to read file name, even if there are media files in `attach-dir`

However, no matter there are media files in `root` or not, all things work as expected on my computer. I can't reproduce your situation, sorry about that. Running `edebug-defun` on `org-media-note-mpv-smart-play` as described above is highly recommended. If you are not familiar with edebug, have a look at  [My work flow to debug emacs plugin | Chen&rsquo;s blog](http://blog.binchen.org/posts/my-work-flow-to-debug-emacs-plugin.html)

Follow the logic, check:
1. if `media-files-in-attach-dir` is the list of media files in `attach-dir`
2. how does the code run? it should runs into `(mpv-play (car media-files-in-attach-dir))` to open file when there's only one file, or `(mpv-play (read-file-name "File to play: " attach-dir))` to let you chose from `attach-dir`

**Comment by yuchen-lea** [comment]
Also, please tell me your media file type ?

**Comment by nanjigen** [comment]
When stepping through with `edebug` and reaching `(media-file-in-attach-dir ...))`, `(org-media-note--media-files-in-dir attach-dir) evaluates to `nil`.

`(attach-dir (if (org-attach-dir)...))` evaluates to my attachment directory just fine earlier in the `func`. If I try Eval while cursor on point in the `org` buffer with `(org-attach-dir)`, the correct `attach-dir` is returned. Further, Eval of `(org-media-note--media-files-in-dir (org-attach-dir))` returns `nil`, so that function is not correctly detecting the media files? The media type is `.mpg`.

After more investigating this is the source of the issue. Moving videos with an extension in the list in `org-media-note--video-types` allows `o` to function. However, even after adding `mpg` to the list with `(add-to-list 'org-media-note--video-types "mpg")`, and seeing it in the list with `(describe-variable)`, it is not detected with any of the above functions

**Comment by yuchen-lea** [comment]
Thanks for your detailed report! 

`mpg` is not included in `org-media-note--video-types`, that's the reason. `org-media-note--video-types` and `org-media-note--audio-types` are used to find media files. `(add-to-list 'org-media-note--video-types "mpg")` should work after you restart the emacs, or you can manually eval function `org-media-note--media-files-in-dir`. 

`mpg` is added to `org-media-note--video-types`, it should fix the no media file error and `nil` prefix mentioned in #7.

**Comment by nanjigen** [comment]
Excellent that fixes it for me!

**Comment by yuchen-lea** [comment]
Happy to hear that and many thanks for your time!
