### ISSUE TITLE
"failed to define function" error after configuration, and running org-media-note-hydra/body

### ISSUE THREAD

**Issue by daraul** [yuchen-lea/org-media-note#60]
I've installed the package using the snippet below, and configured it with the snippet below that one. I'm on the latest version of doom emacs, and emacs 29.

```lisp 
(package! org-media-note :recipe (:host github :repo "yuchen-lea/org-media-note"))
```

```lisp
(use-package! org-media-note
  :hook (org-mode .  org-media-note-mode)
  :bind (
         ("H-v" . org-media-note-hydra/body))  ;; Main entrance
  :config
  (setq org-media-note-screenshot-image-dir "~/.task/attachments/")  ;; Folder to save screenshot
  )
```

When I run `org-media-note-hydra/body` it fails with the error below:

```
apply: Autoloading file .../org-media-note.elc failed to define function org-media-note-hydra/body
```

Any idea what could be going wrong?

**Comment by yuchen-lea** [comment]
Sorry, change `org-media-note-hydra/body` → `org-media-note-show-interface`. I forgot to update the doc.

**Comment by daraul** [comment]
Ah! Great, thanks.
