### ISSUE TITLE
I get a warning about org-attach-dir

### ISSUE THREAD

**Issue by japhir** [yuchen-lea/org-media-note#9]
```elisp
Symbol’s function definition is void: org-attach-dir
```
when I call `org-media-note-hydra/body` and then <kbd>o</kbd>

**Comment by alienzj** [comment]
I also got a warning like this.

**Comment by yuchen-lea** [comment]
That's because `org-attach` is not required before. 

I use another way to declare the `org-attach-dir` function now, have a try ;)

If it still doesn't work, please let me know. 

P.S. you can use `(require 'org-attach)` to temporally fix it.

**Comment by alienzj** [comment]
`(require 'org-attach)` can work.
Thanks ~

**Comment by yuchen-lea** [comment]
`(require 'org-attach)` definitely work. However, I don't want to require the whole since I only use `org-attach-dir`. 

I wonder, does the newest commit fix the warning?

**Comment by japhir** [comment]
I just updated and I do see the new mpv functions, so it looks like updating worked. I still get the error however.
